# Generated by Django 2.2.17 on 2021-01-23 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 18, 49, 6, 798808, tzinfo=utc)),
        ),
    ]
