# Generated by Django 2.2.17 on 2021-01-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210113_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagram',
            old_name='diagram_content',
            new_name='diagram',
        ),
    ]
