# Generated by Django 2.2.17 on 2021-01-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210115_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramstat',
            name='causes',
            field=models.IntegerField(default=0),
        ),
    ]
