# Generated by Django 2.2.17 on 2021-01-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_diagramstat_causes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagramstat',
            name='causes',
        ),
    ]
