# Generated by Django 2.2.19 on 2021-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210318_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='diagrams'),
        ),
    ]
