# Generated by Django 2.2.17 on 2021-01-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210121_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagram',
            old_name='hours_spent',
            new_name='lastTimeSpent',
        ),
        migrations.RenameField(
            model_name='diagramstat',
            old_name='time_Spent',
            new_name='total_time_Spent',
        ),
        migrations.AddField(
            model_name='diagramstat',
            name='causes',
            field=models.IntegerField(default=0),
        ),
    ]
