# Generated by Django 2.2.19 on 2021-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210318_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='preview',
            field=models.TextField(default=''),
        ),
    ]
