# Generated by Django 2.2.17 on 2021-01-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210121_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagramstat',
            old_name='total_time_Spent',
            new_name='totalTimeSpent',
        ),
    ]
