# Generated by Django 2.2.20 on 2021-05-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210502_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonceToToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=False, unique=True)),
                ('nonce', models.CharField(default=False, max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=66),
        ),
    ]
