# Generated by Django 2.2.20 on 2021-05-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210502_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='isRiskComputationShared',
            field=models.TextField(default='{}'),
        ),
    ]
